import { 
  LayoutDashboard, 
  Database, 
  GitCompare, 
  Book, 
  Settings, 
  Bell, 
  Search, 
  User,
  ShieldCheck,
  Eye,
  AlertTriangle,
  CheckCircle2,
  Clock,
  ArrowUpRight,
  Plus,
  Filter,
  Download,
  MoreVertical,
  Table as TableIcon,
  Key,
  Hash,
  Type,
  Calendar,
  ChevronRight,
  ChevronDown,
  FileCode,
  RefreshCw,
  History,
  Trash2,
  Save,
  FileSpreadsheet,
  Upload,
  Terminal,
  Copy
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Designer: Database,
  Drift: GitCompare,
  Dictionary: Book,
  Settings: Settings,
  Notifications: Bell,
  Search: Search,
  User: User,
  Logo: ShieldCheck,
  ShieldCheck: ShieldCheck,
  Eye: Eye,
  Alert: AlertTriangle,
  Success: CheckCircle2,
  Time: Clock,
  External: ArrowUpRight,
  Add: Plus,
  Filter: Filter,
  Export: Download,
  More: MoreVertical,
  Table: TableIcon,
  PK: Key,
  Number: Hash,
  String: Type,
  Date: Calendar,
  ChevronRight: ChevronRight,
  ChevronDown: ChevronDown,
  Code: FileCode,
  Sync: RefreshCw,
  History: History,
  Delete: Trash2,
  Save: Save,
  Excel: FileSpreadsheet,
  Upload: Upload,
  Terminal: Terminal,
  Copy: Copy
};
